### ISSUE TITLE
move note to fluent.ly

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#108]

**Comment by HadadIdan** [comment]
@yossigil  note.java is currently at /fluent.ly/src/main/java/fluent/ly/note.java , would you like it to be at /fluent.ly (project base folder) ?

**Comment by HadadIdan** [comment]
@yossigil  note is currently at \src\main\java\fluent\ly , would you like it to be in the base project folder?

**Comment by EyalFaygen** [comment]
![image](https://user-images.githubusercontent.com/34006139/48793449-a42c9180-ecff-11e8-9454-346ceb8908b1.png)
verified
