### ISSUE TITLE
Upgrade to Java 11: https://goo.gl/xBf7iR

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#126]

**Comment by EyalFaygen** [comment]
@MichaelShohat @HadadIdan @elizabethyeshaayahu320 @OrYasso @Nitzan810 @IlanitSmul 

guys please install java 11 from the link in the title and drop a pic of the eclipse package explorer


![image](https://user-images.githubusercontent.com/34006139/48865194-82064280-edd7-11e8-9587-fc9c15e3baa0.png)

**Comment by OrYasso** [comment]
![image](https://user-images.githubusercontent.com/39669217/48866426-7caaf700-eddb-11e8-9cfc-5890a0c50b97.png)

**Comment by elizabethyeshaayahu320** [comment]
![image](https://user-images.githubusercontent.com/44428417/48869266-45d9de80-ede5-11e8-96c3-cfc958826968.png)

**Comment by MichaelShohat** [comment]
![image](https://user-images.githubusercontent.com/38256261/48869413-c1d42680-ede5-11e8-8dfd-deb7d72273a9.png)

**Comment by Nitzan810** [comment]
![chillypepper](https://user-images.githubusercontent.com/44426817/48886152-78122d00-ee33-11e8-9136-1c65cb9b0d80.png)

**Comment by IlanitSmul** [comment]
![jdk11](https://user-images.githubusercontent.com/37686204/48889458-a9442a80-ee3e-11e8-8780-7f64b1c53a72.PNG)

**Comment by HadadIdan** [comment]
![image](https://user-images.githubusercontent.com/44426929/48968296-18b04a80-eff6-11e8-90bc-64816965fdbf.png)

Every member posted "proof" pictrue, closed.
