### ISSUE TITLE
Make sure all tests conform to the recommended maven structure

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#14]

**Comment by MichaelShohat** [comment]
![screenshot_1](https://user-images.githubusercontent.com/38256261/47780516-32ff4d00-dd04-11e8-90f4-a4a66fc0ec6c.png)

JUnit tests ran when project was added as a new Maven project.

**Comment by yossigil** [comment]
they should be in a designated test folder as per the maven convention

**Comment by HadadIdan** [comment]
done

**Comment by yossigil** [comment]
![image](https://user-images.githubusercontent.com/12775400/48222821-36e33d00-e39e-11e8-91b2-5d7d4f65e9c6.png)
NO, IT IS NOT.

next time  you close it, show a screen dump

**Comment by EyalFaygen** [comment]
![image](https://user-images.githubusercontent.com/34006139/48442616-5a8bf600-e797-11e8-8245-94e0805e2662.png)


done

**Comment by yossigil** [comment]
OOPS... still wrong. There are 74 tests in the src/main

**Comment by EyalFaygen** [comment]
@yossigil i couldnt find any "@Test" anotation or any test classes under src/main.
can you help me refine my search?

**Comment by EyalFaygen** [comment]
![image](https://user-images.githubusercontent.com/34006139/48793341-56b02480-ecff-11e8-9fda-d742860ff421.png)

done
