### ISSUE TITLE
LGTM integration doesn't work

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/team6#145]
LGTM should update it's result for every commit, or at least every day, but for some reason it doesn't.
I spent hours on it and I can't seem to undertand what is the problem. For example, at the moment it shows the project have some errors and warning that are already solved withing the master branch, and the last commit specified there is from many days ago. Something doesn't work, and I dont know why. Please help.
@OrYasso @EyalFaygen @IlanitSmul @elizabethyeshaayahu320 @Nitzan810 @MichaelShohat

**Comment by EyalFaygen** [comment]
1. Im not entirely sure that LGTM can do what you are asking, as its working with pull requsts

2. i dont think this is an issue, we are now in the beginning of sprint 1, and we are using the pull request mechanism (as instructed last wednesday), that you and I tested with LGTM

**Comment by HadadIdan** [comment]
> 
> 
>     1. Im not entirely sure that LGTM can do what you are asking, as its working with pull requsts
> 
>     2. i dont think this is an issue, we are now in the beginning of sprint 1, and we are using the pull request mechanism (as instructed last wednesday), that you and I tested with LGTM

When I asked @yossigil about LGTM he said it should work with commits, like Travis.

**Comment by HadadIdan** [comment]
After asking friends and consulting Google, apparently it works as expected. It updates it's alerts information based on Pull Requests. Closed.
