### ISSUE TITLE
Setup continuous integration

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#15]

**Comment by elizabethyeshaayahu320** [comment]
איזה כלי בדיוק להוריד?

**Comment by MichaelShohat** [comment]
![screenshot_2](https://user-images.githubusercontent.com/38256261/47780707-95f0e400-dd04-11e8-8f1e-f6298ab6fa1d.png)
Travis CI build successful, now we'll run tests

**Comment by yossigil** [comment]
Please note that maven does not know how to run the tests if they are not in a good place. This must be fixed.

**Comment by HadadIdan** [comment]
now the tests will run (from test folder)
