### ISSUE TITLE
Test out the merge and pull request system

### ISSUE THREAD

**Issue by MichaelShohat** [TechnionYP5779/team6#154]

**Comment by MichaelShohat** [comment]
#153

**Comment by HadadIdan** [comment]
Removed @EyalFaygen from assignment, as instructed to us to have only 1 assigned to each issue.

**Comment by yossigil** [comment]
Thanks. Also, please define what would be the outcome of this issue, e.g., when do we know it is done?

**Comment by MichaelShohat** [comment]
@yossigil I'm closing this issue now,
I wanted to make sure that the need review label is shown clear enough in the pull request tab and after making sure everyone looked at #88 again (and the fact pull requests were used before) this issue is redundant now.
