### ISSUE TITLE
Find a suitable package for user managment

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/team6#161]
Including but not limited to: Password encryption, Password Recovery, etc.

**Comment by yossigil** [comment]
check out what other teams did. Include a brief summary of options before closing this isue

**Comment by elizabethyeshaayahu320** [comment]
i found about UserForsting ,it runs on Ubuntu . 
 https://www.userfrosting.com/
we need to learn about lavarel,php
@EyalFaygen  i need your opinion about it. if it suitable for us?

**Comment by EyalFaygen** [comment]
@elizabethyeshaayahu320  i think userfrosting is a bit too much work as it doesnt support java/javscript and we meed a workaround to integrate it in to our project.

as i was reading i found [okta](https://developer.okta.com/) which provides a simple user managment api we can use in front end 
what do you think?

**Comment by elizabethyeshaayahu320** [comment]
i think it is not free

**Comment by EyalFaygen** [comment]
its free for up to 1000 monthly active users
