### ISSUE TITLE
Create a GUI for the Parking Renting Project

### ISSUE THREAD

**Issue by IlanitSmul** [TechnionYP5779/team6#162]
The division of the task between @IlanitSmul and @EyalFaygen will be determined later.

**Comment by yossigil** [comment]
Did you select a GUI framework?

**Comment by IlanitSmul** [comment]
See the following pull requests:
* Create an Angular Project: #189.
* "Home" page: #281.
* "Login", "Sign Up", "Sign Out" pages: #210, #213, #241, #248.
* "My Profile" page: #287, #290.
* "Become a Host" page: #194, #236, #248.
* "Find Parking" page: #235, #243, #248, #268, #279.
