### ISSUE TITLE
Learn about and add a GET handler for the server

### ISSUE THREAD

**Issue by MichaelShohat** [TechnionYP5779/team6#166]

**Comment by HadadIdan** [comment]
created GET handler here:
https://github.com/TechnionYP5779/team6/commit/4686d42e42e8ef4768179f705f0285e128d00bfc
Shouldn't have done it because it was Michael's job, forgot about it, won't happen again.

**Comment by MichaelShohat** [comment]
Closing this issue, I read about and looked into GET in https://github.com/TechnionYP5779/team6/commit/ca924ec45179cec97cb1f694c1c6c462848615ca
