### ISSUE TITLE
Unit tests for class Bool

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#17]

**Comment by yossigil** [comment]
please provide refernce to commit

**Comment by HadadIdan** [comment]
commit reference: https://github.com/TechnionYP5779/team6/commit/1f961911bfcde78c58c352ae1c6dda5d229cfc09

**Comment by yossigil** [comment]
again, you are not supposed to use  assertTrue(ct.inner==cf.inner);

**Comment by yossigil** [comment]
@SuppressWarnings("static-method")
was supposed to occur only once.

**Comment by HadadIdan** [comment]
@yossigil why? please elaborate,

**Comment by yossigil** [comment]
#86

**Comment by HadadIdan** [comment]
@OrYasso fixed this
