### ISSUE TITLE
write a wiki about the our classes hierarchy  

### ISSUE THREAD

**Issue by elizabethyeshaayahu320** [TechnionYP5779/team6#174]

**Comment by HadadIdan** [comment]
@OrYasso and @Nitzan810  I assigned you both, please decide between you who is in charge
of that and remove the other from the assignment.

**Comment by Nitzan810** [comment]
Wrote the page, it is [here](https://github.com/TechnionYP5779/team6/wiki/Parking-Project-Class-Hierarchy).
