### ISSUE TITLE
Unit tests for class box

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#18]

**Comment by HadadIdan** [comment]
added tests

**Comment by yossigil** [comment]
maybe have a team member check this?

**Comment by HadadIdan** [comment]
commits reference: https://github.com/TechnionYP5779/team6/commit/62fd653a484cf922973343d82b7da85cc0bb248f
and
https://github.com/TechnionYP5779/team6/commit/c38eb031aaa4d7d97fd2c56ede4acd0debc2248d

**Comment by yossigil** [comment]
make sure you use boxing interface, not intValue etc #81

**Comment by HadadIdan** [comment]
@yossigil I didn't use boxing interface here because I tested the boxing interface here.
