### ISSUE TITLE
Download the MySQL connector

### ISSUE THREAD

**Issue by Nitzan810** [TechnionYP5779/team6#221]
Simply do steps 1 and 2 in this guide: https://github.com/TechnionYP5779/team6/wiki/Integrating-SQL.
You can do step 4 if you want to verify it's working on your end.
Comment "done" below once you have done it.

**Comment by OrYasso** [comment]
done

**Comment by HadadIdan** [comment]
done

**Comment by EyalFaygen** [comment]
done

**Comment by MichaelShohat** [comment]
done

**Comment by elizabethyeshaayahu320** [comment]
Done

**Comment by HadadIdan** [comment]
Done

**Comment by HadadIdan** [comment]
Done

**Comment by IlanitSmul** [comment]
done
