### ISSUE TITLE
Add external GSON jar

### ISSUE THREAD

**Issue by OrYasso** [TechnionYP5779/team6#238]
Add the following jar file to the project like we did before:
https://search.maven.org/remotecontent?filepath=com/google/code/gson/gson/2.8.5/gson-2.8.5.jar

write done when you finish

**Comment by MichaelShohat** [comment]
done

**Comment by HadadIdan** [comment]
done

**Comment by Nitzan810** [comment]
done

**Comment by HadadIdan** [comment]
Done

**Comment by IlanitSmul** [comment]
done

**Comment by EyalFaygen** [comment]
done
