### ISSUE TITLE
make sure all code is spartanized

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#47]

**Comment by yossigil** [comment]
![image](https://user-images.githubusercontent.com/12775400/48544635-b0ae8580-e8cc-11e8-9757-3921a554626a.png)


Not done...

**Comment by MichaelShohat** [comment]
![image](https://user-images.githubusercontent.com/38256261/48869605-838b3700-ede6-11e8-970c-43336c32de96.png)

**Comment by MichaelShohat** [comment]
commit is - forgot to close with it

https://github.com/TechnionYP5779/team6/commit/7496a368734bb4294e9b32692f8754c6da0b665a

**Comment by EyalFaygen** [comment]
verified #76
