### ISSUE TITLE
make sure all team members have a proper icon, as per the instructions

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#54]
- [x] identify this member
- [x] say nu nun nu
- [x] fix the problem

**Comment by yossigil** [comment]
eyal, please make sure you follow all instructions in the tutorial. include here reference to the issues you created

**Comment by EyalFaygen** [comment]
@yossigil do you mean #3  ?  if not, please be more specific bcause i dont understand whats missing

**Comment by EyalFaygen** [comment]
do you mean the checkboxes in the issue? i have checked them. 
other than that i still don't understand whats missing

**Comment by yossigil** [comment]
please include refs to the issues you created during the tutorial

**Comment by yossigil** [comment]
@EyalFaygen ; did you create a Karma/Todo issue? can you please add a reference here to this issue

**Comment by EyalFaygen** [comment]
and the only thing i found was [this](https://github.com/SpartanRefactoring/Main/issues/330) regarding karma/todo

i created (and closed) issue #66 .

if that is not what you meant, please tell me.

**Comment by yossigil** [comment]
Question was: did you create a Karma/Todo issue? can you please add a reference here to this issue

A more efficient answer would be: Yes + reference
