### ISSUE TITLE
Every member need to decide 1-2 project ideas

### ISSUE THREAD

**Issue by OrYasso** [TechnionYP5779/team6#55]
- [x] Or
- [x] Idan
- [x] Michael
- [x] Eyal
- [x] Nitzan
- [x] Elizabeth
- [x] Ilanit

until date: 14/7

**Comment by yossigil** [comment]
make issues and assign them to each team member.
set a milestone. attach to each issue

**Comment by HadadIdan** [comment]
@yossigil See issues #67 #68 #69 #70 #71 #72 #73 , and let me know if this is what you had in mind so i can close.
