### ISSUE TITLE
Fix your eclipse projects

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#57]
Currently the whole structure is like this:

![image](https://user-images.githubusercontent.com/12775400/48151811-e949d000-e2ca-11e8-91e2-5dd18a8ea071.png)

to reproduce, import the project through eclipse git repos's and then ask eclipse to open all projects inside the repo.

**Comment by HadadIdan** [comment]
@yossigil יכול להיות שזה מופיע בצורה הזאת כי לא פתחת בתור פרוייקט מייבן? כי לכולנו עובד הפרוייקט

**Comment by HadadIdan** [comment]
הערה של @yossigil :
עליכם לגרום לכך שמבנה הפרויקט האקליפסי יהיה תקין. כלומר, זה צריך להתקמפל גם כפרויקט אקליפסי, ללא תלות במייבן.

**Comment by yossigil** [comment]
did you check that import shows now eclipse projects?

**Comment by MichaelShohat** [comment]
![image](https://user-images.githubusercontent.com/38256261/48220035-e0becb80-e396-11e8-804d-1dbecec7e33c.png)

**Comment by yossigil** [comment]
thanks, good job
