### ISSUE TITLE
Use TDD to develop function iterables.alternate

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#60]
Use TDD to develop a function iterables.alternate that takes two iterables over elements of the same kind, and returns an iterable that returns elements in these in alternating order, until the shortest one is exhausted, and then continues with the other.

use TDD to design and implement specification for the case that one or both arguments are null.
be sure to break tests before you write any line of code.

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#94

**Comment by IlanitSmul** [comment]
reopen for issue #76

**Comment by EyalFaygen** [comment]
verified #76
