### ISSUE TITLE
use TDD to define class angle

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#62]
that represents an angle on the plane; angles can be added, negated and substracted
here are some hints.

- [x] angle.degrees(20) creates an angle of 20 degrees
- [x] angle.radians(1) creates an angle of 1 radian
- [x] angle.pi is an angle of pi radians
- [x] angle.halfPi is an engle of half Pi radians
- [x] angle.halfPi.add(angle.degrees(20)) is an engle of half Pi radians + 20 radians
- [x] angle.halfPi.add((20)) is an engle of half Pi radians + 20 degrees
- [x] angle.pi.degrees() is 180
- [x] angle.of(20).degrees() is 180
- [x] angle.pi.radians() is PI/2

be sure to create code that try to cheat the tests, e.g. 
`class angle { static angle degrees(double x) { return new angle(20); }`

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#96

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#91

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#71

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#54

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team1#58

**Comment by MichaelShohat** [comment]
@yossigil Some of my code is logic driven (based on my initial testing):
`conversionConstDegToRad = Math.PI/180;`
`degrees = i;`
`radians = i*conversionConstDegToRad;`

and some is test cheating:
  `public double radians() {`
    `if (radians == Math.PI) return Math.PI/2;`
    `return radians;`
 ` }`
coverage:
![image](https://user-images.githubusercontent.com/38256261/48315098-c5440280-e5da-11e8-8f10-c182152aee55.png)

Can this issue be closed?

**Comment by EyalFaygen** [comment]
verified #76
