### ISSUE TITLE
add some more descriptive stuff in your readme.md file

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#64]
remember this is how people will see you project on the web

**Comment by HadadIdan** [comment]
@yossigil please see readme.md file and let me know if there is something you would like me to add.
Also, please give me a link to the original Spartan Project, so I can reference it there.

**Comment by yossigil** [comment]
@HadadIdan : 

- You are responsible on completing the issue. I cannot check every bit. I check completion sampling issues, not all. take a look at what others did.
- I will let you use Google yourself.

**Comment by HadadIdan** [comment]
Closed because this is the result of using Google myself.

**Comment by yossigil** [comment]
@HadadIdan : please ask one of your team members to close the issue, after he or she verified what you did

**Comment by HadadIdan** [comment]
@EyalFaygen Please verify the issue and close it.
Also, @EyalFaygen added lgtm badgets at https://github.com/TechnionYP5779/team6/commit/5691c1c07c6b95902e91a34525014208e838f840 and https://github.com/TechnionYP5779/team6/commit/74f379ceadb2b2ba38318655da249e37db38c427
