### ISSUE TITLE
Have a 1-2 project ideas by 14.11 (Idan)

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/team6#67]

**Comment by HadadIdan** [comment]
I have a project idea.

**Comment by yossigil** [comment]
WHERE IS YOUR PROJECT IDEA, IT MUST BE HERE.

**Comment by HadadIdan** [comment]
@yossigil 
My project idea was to create WIFI-based chat, allowing people connected to the same WIFI to communicate with instant messaging, This has many application, starting from the very basic chat implementation and onto adding security and file transfers. The usage will be at Lectures in a foreign Location, Parties, Bars and more.
