### ISSUE TITLE
Have a 1-2 project ideas by 14.11 (Ilanit)

### ISSUE THREAD

**Issue by HadadIdan** [TechnionYP5779/team6#72]

**Comment by IlanitSmul** [comment]
I have a project idea.

**Comment by IlanitSmul** [comment]
![-](https://user-images.githubusercontent.com/37686204/48695882-00e95880-ebe9-11e8-848b-dbb2951118de.PNG)

**Comment by yossigil** [comment]
pLEASE CONVERT TO TEXT

**Comment by IlanitSmul** [comment]
##  <div dir="rtl">אפליקציה לניהול אירועים</div>

###  <div dir="rtl">לפני האירוע:</div>

<div dir="rtl">- ניהול רשימת אורחים:</div>
<div dir="rtl">   1. שליחת הזמנות: או באמצעות הזמנה להצטרפות לאפליקציה, או באמצעות קישור לאמצעי תקשורת רגילים כמו WhatsApp.</div>
<div dir="rtl">   2. ניהול אישורי הגעה.</div>

<br/>
<div dir="rtl">- חלוקת האורחים לקטגוריות (משפחה, חברים, עבודה), וקבלת תכנית לסידור השולחנות באופן אוטומטי ובאמצעות הכנסת פרמטרים נוספים על האולם, כמו: מס' השולחנות, כמות אורחים בשולחן, מיקומם היחסי באולם, ועוד. </div>
<div dir="rtl">עדכון כל אורח במיקום שהוקצה לו (באמצעות מפה של האולם).</div>

<br/>
<div dir="rtl">- אורחים שיבחרו להתחבר לאפליקציה יוכלו למלא פרטים נוספים, כמו: </div>
<div dir="rtl">העדפות ספציפיות למנות: כשרות, צמחוניות, ללא גלוטן, וכו'.</div>
<div dir="rtl">כתובת שבאמצעותה יוכלו לקבל הוראות הגעה לאולם דרך קישור לאמצעי ניווט מתאים (כמו Waze). </div>

###  <div dir="rtl">תוך כדי האירוע:</div>
<div dir="rtl">- נסיעות משותפות: חיפוש טרמפים של אורחים בסביבה.</div>
<br/>
<div dir="rtl">- העברת צ'ק באופן אלקטרוני.</div>
<br/>
<div dir="rtl">- ארגון אלבום תמונות משותף בתוך האפליקציה שאליו האורחים יוכלו להעלות תמונות.</div>
<br/>
<div dir="rtl">- קבלת מיקום (GPS) של חברים אחרים שמחוברים לאפליקציה והגיעו לאירוע.</div>

###  <div dir="rtl">לאחר האירוע:</div>
<div dir="rtl">- הוצאת נתונים סטטיסטיים, למשל רישום המתנות והצ'קים והוצאה ל-excel.</div>
<br/>
<div dir="rtl">- העלאת סרט/תמונות האירוע (המקצועיות) לאפליקציה.</div>
<br/>
<div dir="rtl"> - מתן ביקורת על האולם.</div>

###  <div dir="rtl">השתלבות בעלי האולמות באפליקציה:</div>
<div dir="rtl">- יוכלו להעלות תפריטים, תמונות של המקום, ביקורות של אורחים, וכו'.</div>

###  <div dir="rtl">השתלבות מפרסמים באפליקציה:</div>
<div dir="rtl">- יוכלו להעלות פרסומות רלוונטיות, למשל: צלמים, חנויות תכשיטים, וכו'.</div>
