### ISSUE TITLE
Reopen all non-trivial issues, and make sure that someone else closes them

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#76]
in particular, if you closed an non-trivial issue, reopen it, and ask someone else in your team verifies that the issue can be closed.

**Comment by yossigil** [comment]
trivial issues are e.g., duplicate issues, or setup

**Comment by yossigil** [comment]
Do not close this issue, without demonstrating that you indeed fixed some closed issues.

**Comment by yossigil** [comment]
Do not close this issue, without demonstrating that you indeed fixed some closed issues.

**Comment by yossigil** [comment]
Please add a commit number for all issues that were closed without a commit number.
This is an exercise in searching git history

**Comment by yossigil** [comment]
all open/reclosed issues should include a reference to this issue...

**Comment by HadadIdan** [comment]
@Nitzan810 will close eyal's issue..
@EyalFaygen will close other issue.

**Comment by Nitzan810** [comment]
Closed all of Eyal's issues that didn't involve anyone else on the team.
If I missed any please comment here.

**Comment by EyalFaygen** [comment]
i believe this are all of them, thus closed
