### ISSUE TITLE
Consolidate classres Range and range

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#77]
if you created class Range (capitalized).

The correct design should  have three (internal?) classes,
one for infinite range bounded above,
another for infinite bounded below
and a third for a finite range.

for example,
range.to(3).to(2) generates an error,
range.to(3).fron(2) creates a finite range,

the person responsible for this should not be the person who wrote class Range

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#78

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#63

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#81

**Comment by yossigil** [comment]
what's up?

**Comment by yossigil** [comment]
hint, you need three different classes, for the three kinds of ranges, each supporting different functions
