### ISSUE TITLE
Document a push procedure in a wiki page

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#78]
Should include formatting, cleanup, tests, spartanization etc.

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#122

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#107

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#80

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#62

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#77

**Comment by yossigil** [comment]
Assign someone for this issue and do it

**Comment by IlanitSmul** [comment]
@yossigil 

What does "**cleanup**" mean?
I saw that the other teams received an issue called "_Create a cleanup profile for eclipse, and save it with your project_", but we did not receive it. Does this apply to us as well?

**Comment by yossigil** [comment]
make sure that all team members understand this

**Comment by IlanitSmul** [comment]
@elizabethyeshaayahu320 @Nitzan810 @MichaelShohat @HadadIdan @OrYasso @EyalFaygen 
Please read the following wiki page: [Push Procedure](https://github.com/TechnionYP5779/team6/wiki/Push-Procedure)
