### ISSUE TITLE
Check again that you do not use junit Assert, but only class azzert

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#79]
You can do this manually, or write a script. it is up to you.

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#76

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#61

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#79

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#106

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#121

**Comment by EyalFaygen** [comment]
see #56

**Comment by yossigil** [comment]
![image](https://user-images.githubusercontent.com/12775400/48516514-39e1a000-e86c-11e8-86f3-27ac52a0afae.png)

**Comment by yossigil** [comment]
Maybe use Ctrl-Shift-G

**Comment by EyalFaygen** [comment]
![image](https://user-images.githubusercontent.com/34006139/48729075-5fd9bc80-ec3f-11e8-9d7f-d0b711f27917.png)
