### ISSUE TITLE
consolidate function unused into interface forget

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#80]
they do the same; refactor the code accordingly

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#120

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#105

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#78

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#75

**Comment by yossigil** [comment]
oops, irrelevant

**Comment by OrYasso** [comment]
@yossigil hey yossi, there is a function called "unuse" instead of "unused", should it be changed to "unused" and moved to interface forget too?
![image](https://user-images.githubusercontent.com/39669217/48677835-7fabaa80-eb83-11e8-91e9-3947f6bf8a14.png)

**Comment by yossigil** [comment]
yes

**Comment by yossigil** [comment]
change to forget.it
