### ISSUE TITLE
Test runs should be with assertions enabled

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#82]
Play with eclipse, it is better to write
`assert x`
then
`azzert.isTrue(x)`

but when you run tests the jvm should have assertions enabled

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#81

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#66

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#84

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#111

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#126

**Comment by yossigil** [comment]
You should use a jvm flag. Can you please show where this flag is set? use screen dump if necessary

**Comment by IlanitSmul** [comment]
The flag "ea" is already in use (defaulted by Eclipse):
![assert](https://user-images.githubusercontent.com/37686204/48782560-22c90500-ece7-11e8-8b15-48d9e887a3b3.PNG)
