### ISSUE TITLE
Integrate github issues with eclipse

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#83]
for this, you need a proper mylyn connector. Best done by one team member figruing this out, and then
letting him instruct other members.

in short, github issues should be shown in the eclipse task list view.

![image](https://user-images.githubusercontent.com/12775400/48472870-e174b900-e7ff-11e8-8357-cf6c77bd12c5.png)

this is what the end results looks like in my machine. I can even see this issue on my eclipse:

![image](https://user-images.githubusercontent.com/12775400/48473379-03bb0680-e801-11e8-99b9-64c5d470c03a.png)

**Comment by yossigil** [comment]
![image](https://user-images.githubusercontent.com/12775400/48473035-3dd7d880-e800-11e8-8753-e906d36a448d.png)

this is where you add repos.

**Comment by yossigil** [comment]
hint, do an internet search

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team5#127

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#82

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#67

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team3#85

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#112

**Comment by MichaelShohat** [comment]
@yossigil Is there a preferred plugin?
![image](https://user-images.githubusercontent.com/38256261/48474559-7b8a3080-e803-11e8-91c2-395e6da28c47.png)

**Comment by yossigil** [comment]
all hints are on the issue; please check also  how others did it.
Next time, if you encounter several plugins, can you phrase the question more informatively.
Why do you want one and not the other.
i.e, when you get an issue, do not make this an issue for the person who opened it...

**Comment by EyalFaygen** [comment]
wiki guide:
https://github.com/TechnionYP5779/team6/wiki/Integrate-github-issues-with-eclipse

final result:
![image](https://user-images.githubusercontent.com/34006139/48736233-62461180-ec53-11e8-9603-b1fea7532f20.png)



@MichaelShohat  @IlanitSmul  @HadadIdan @Nitzan810 @elizabethyeshaayahu320 @OrYasso 
please follow the wiki guide and post pic after

**Comment by IlanitSmul** [comment]
![issues](https://user-images.githubusercontent.com/37686204/48804441-4ad35b00-ed1d-11e8-9432-1bf0c5f75d8e.PNG)

**Comment by HadadIdan** [comment]
![image](https://user-images.githubusercontent.com/44426929/48824770-00c69580-ed6e-11e8-8025-593ad2b0dcee.png)

**Comment by elizabethyeshaayahu320** [comment]
![image](https://user-images.githubusercontent.com/44428417/48825916-826bf280-ed71-11e8-824c-5bfeb39e9808.png)

**Comment by elizabethyeshaayahu320** [comment]
![image](https://user-images.githubusercontent.com/44428417/48826074-0f16b080-ed72-11e8-930a-b25b909470f0.png)

**Comment by OrYasso** [comment]
![image](https://user-images.githubusercontent.com/39669217/48843328-68490900-ed9f-11e8-8fd7-362609c7fe03.png)

**Comment by MichaelShohat** [comment]
![image](https://user-images.githubusercontent.com/38256261/48843427-ba8a2a00-ed9f-11e8-97d5-26b504bc29b4.png)

**Comment by Nitzan810** [comment]
![softmachine](https://user-images.githubusercontent.com/44426817/48864652-e6280700-edd5-11e8-816f-9c24e57020dd.png)

**Comment by OrYasso** [comment]
@EyalFaygen can we close this?
