### ISSUE TITLE
connect your project to SonarQube

### ISSUE THREAD

**Issue by dormaayan** [TechnionYP5779/team6#85]
_From @yossigil on November 14, 2018 9:40_

for now, just connect. later we shall decide which rules to use.

_Copied from original issue: TechnionYP5779/team5#128_

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team1#83

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team2#68

**Comment by dormaayan** [comment]
This issue was moved to TechnionYP5779/team4#113

**Comment by EyalFaygen** [comment]
because of some unknown problem i cant see (or select) the TechnionYP5779 and the team6 repo, in sonarCloud.io. @dormaayan  do you know if this is an ownership issue?

**Comment by EyalFaygen** [comment]
done d2d6a181acba7ae9a9591db295198c939862aecf

**Comment by EyalFaygen** [comment]
fixed travis and sonarCloud 078701050c399c5e3a748f2710d6e028a33fd04d
