### ISSUE TITLE
  @SuppressWarnings("boxing")

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#87]
This should never occur in the code, perhaps with the exception of class "box"
Use class box, and/or box.it() instead.

Only close this issue with a screen dump showing search for   @SuppressWarnings("boxing")

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#129

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#114

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#90

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#69

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team1#85

**Comment by Nitzan810** [comment]
Closing issue with picture.
![boxing](https://user-images.githubusercontent.com/44426817/48673685-a00c4280-eb4c-11e8-9ac3-7a37305fbaf9.png)

**Comment by Nitzan810** [comment]
Forgot we need other people to close an issue, so reopened.

**Comment by yossigil** [comment]
Also, it could be a SuppressWarning({xx, "boxing", }), check that as well.

**Comment by Nitzan810** [comment]
Removed all boxing suppresion I could find.
![sutickyfingars](https://user-images.githubusercontent.com/44426817/48798022-66823580-ed0c-11e8-968a-d4ca81e69268.png)
