### ISSUE TITLE
Create a cleanup profile for eclipse, and save it with your projecrt

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#88]
Connect this profile with the wiki you created for a commit procedure

![image](https://user-images.githubusercontent.com/12775400/48479501-315b7c00-e810-11e8-997e-c2a63792c609.png)

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#131

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#116

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#92

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#71

**Comment by yossigil** [comment]
add the cleanup profile to the git

**Comment by IlanitSmul** [comment]
- I push the cleanup profile to git in commit 73f3aaf453da6be95ce54ae57fdf093e6653aea3.
- Also, I add to wiki instructions for how to import the profile into Eclipse. See [link to wiki](https://github.com/TechnionYP5779/team6/wiki/Instructions-for-import-the-%22Clean-Up-Profile%22-into-Eclipse).

**Comment by IlanitSmul** [comment]
@elizabethyeshaayahu320 @Nitzan810 @MichaelShohat @HadadIdan @OrYasso @EyalFaygen 
Please read the following wiki page: [Instructions for import the "Clean Up Profile" into Eclipse](https://github.com/TechnionYP5779/team6/wiki/Instructions-for-import-the-%22Clean-Up-Profile%22-into-Eclipse)

**Comment by yossigil** [comment]
I don't think this was done. I applied cleanup and I got many changes.

![image](https://user-images.githubusercontent.com/12775400/49218267-aade9700-f3d8-11e8-915b-070fbbb3061f.png)

**Comment by HadadIdan** [comment]
@IlanitSmul @EyalFaygen @MichaelShohat @Nitzan810 @elizabethyeshaayahu320 @OrYasso 
Please make sure you followed the instructures here:
https://github.com/TechnionYP5779/team6/wiki/Instructions-for-import-the-%22Clean-Up-Profile%22-into-Eclipse and like this comment to indicate you did.

**Comment by HadadIdan** [comment]
Also, see the comment here: 
https://github.com/TechnionYP5779/team6/issues/160#issuecomment-442892452
