### ISSUE TITLE
Convert azzert.that(X, is(true)) to assert x

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5779/team6#90]
Similalry, convert azzert.that(X, is(false)) to assert !x
Similalry, convert azzert.thattrue, is(Boolean.FALSE)) to assert !x,
etc.

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team5#133

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team4#119

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team3#93

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team2#75

**Comment by yossigil** [comment]
This issue was moved to TechnionYP5779/team1#90

**Comment by EyalFaygen** [comment]
vrified #76
